### ISSUE TITLE
Metrics metadata

### ISSUE THREAD

**Issue by swardlincoln** [billg-splunk/bg-utils#1]
https://github.com/billg-splunk/bg-utils/blob/899c366f70d8cf80da00b00f5e028620a99f1ddc/Scripts/getMetricMetadata.py#L16

Limit is 10,000 for the API. Anything above that will throw a status code > 200. 
It still seems that the data is truncated with certain letters. Is there any way to get past this?

**Comment by billg-splunk** [comment]
I will have it paginate and go through it until it gets the last page.

I had it looking for "a*"; I've fixed it to just use "*". Is this what you mean?

**Comment by swardlincoln** [comment]
Yup. That works.
